from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('messages/', views.user_messages, name='user_messages'),
    path('messages/request-limit/', views.request_card_limit_increase, name='request_card_limit_increase'),
    path('create/', views.create_card, name='create_card'),
    path('card/<slug:slug>/', views.view_card, name='view_card'),
    path('card/<slug:slug>/edit/', views.edit_card, name='edit_card'),
    path('card/<slug:slug>/request-upgrade/', views.request_upgrade, name='request_upgrade'),
    path('my-admin/login/', views.admin_login_view, name='admin_login'),
    path('my-admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('my-admin/messages/', views.admin_messages, name='admin_messages'),
    path('my-admin/card/<slug:slug>/edit/', views.admin_edit_card, name='admin_edit_card'),
    path('my-admin/card/<slug:slug>/toggle-status/', views.admin_toggle_card_status, name='admin_toggle_card_status'),
    path('my-admin/card/<slug:slug>/delete/', views.delete_card_admin, name='delete_card_admin'),
    path('my-admin/user/<int:user_id>/card-limit/', views.admin_set_card_limit, name='admin_set_card_limit'),
    path('my-admin/user/<int:user_id>/delete/', views.delete_user_admin, name='delete_user_admin'),
    path('my-admin/messages/<int:request_id>/<str:action>/', views.admin_handle_upgrade, name='admin_handle_upgrade'),
    path('documentation/', views.documentation_view, name='documentation'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('export/csv/', views.export_cards_csv, name='export_cards_csv'),
    path('export/excel/', views.export_cards_excel, name='export_cards_excel'),
]
