# Generated by Django 5.2.4 on 2025-08-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_style_json',
        ),
        migrations.RemoveField(
            model_name='card',
            name='message',
        ),
        migrations.RemoveField(
            model_name='card',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='title',
        ),
        migrations.AddField(
            model_name='card',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_data',
            field=models.JSONField(default=dict),
        ),
    ]
