# Generated by Django 5.2.4 on 2025-08-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_card_card_style_json_remove_card_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
