# Generated by Django 5.2.4 on 2025-08-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='text_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
