# Generated by Django 5.0.1 on 2024-07-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_profile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='unique_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
