# Generated by Django 5.0.1 on 2024-07-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_backfill_slug_and_deactivate_duplicates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='unique_slug',
        ),
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
