# Generated by Django 5.2.5 on 2025-09-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_finalize_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
