# Generated by Django 5.2.5 on 2025-09-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_alter_card_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='text_color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
    ]
