# Generated by Django 5.2.5 on 2025-09-21 09:35

from django.db import migrations, models


def _reset_existing_otps(apps, schema_editor):
    Profile = apps.get_model('cards', 'Profile')
    Profile.objects.update(otp=None, otp_expires_at=None, otp_requested_at=None, otp_attempts=0)


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_card_logo_alter_card_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='otp',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.RunPython(_reset_existing_otps, migrations.RunPython.noop),
    ]
