# Generated by Django 5.2.5 on 2025-09-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_profile_otp_attempts_profile_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
