# Generated by Django 5.2.5 on 2026-07-10 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_card_updated_at_cardchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('save', 'Save contact'), ('wallet', 'Wallet add'), ('lead', 'Lead submitted')], max_length=16)),
                ('target', models.CharField(blank=True, max_length=120)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('referrer', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='cards.card')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['card', 'kind', 'created_at'], name='cards_cardi_card_id_5bf268_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(blank=True)),
                ('utm_source', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('new', 'New'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='cards.card')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['card', 'status', 'created_at'], name='cards_leadc_card_id_21aa77_idx')],
            },
        ),
    ]
