# Generated by Django 5.2.5 on 2026-07-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0020_add_premium_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_reset_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_reset_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
