# Generated by Django 5.2.5 on 2026-07-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_profile_password_reset_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='slug_customized',
            field=models.BooleanField(default=False, help_text='Set to True after the owner uses their one-time public-URL change.'),
        ),
    ]
