# Generated by Django 5.2.5 on 2026-07-13 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0022_card_slug_customized'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='card',
            name='last_warning_stage',
            field=models.PositiveSmallIntegerField(default=0, help_text='Highest warning stage already sent (30/7/1 → 1/2/3). Prevents re-sending.'),
        ),
        migrations.AddField(
            model_name='card',
            name='lifecycle_status',
            field=models.CharField(choices=[('trial', 'Trial (first 12 months)'), ('active_paid', 'Paid'), ('expiring_soon', 'Expiring soon'), ('expired', 'Expired — offline'), ('admin_disabled', 'Disabled by admin')], default='trial', max_length=24),
        ),
        migrations.AddField(
            model_name='card',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_paid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CardLifecycleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('trial_started', 'Trial started'), ('warning_30d', '30-day warning sent'), ('warning_7d', '7-day warning sent'), ('warning_1d', '1-day warning sent'), ('expiring_soon', 'Marked expiring soon'), ('trial_ended', 'Trial ended'), ('deactivated', 'Deactivated (offline)'), ('reactivated', 'Reactivated (back online)'), ('renewed', 'Renewed (paid)'), ('admin_override', 'Admin override')], max_length=32)),
                ('actor', models.CharField(choices=[('system', 'System (cron)'), ('admin', 'Admin'), ('user', 'User')], default='system', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, help_text='Admin user who triggered the action (only for actor=admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_logs', to='cards.card')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['card', 'created_at'], name='cards_cardl_card_id_d1ad8c_idx'), models.Index(fields=['action', 'created_at'], name='cards_cardl_action_6b46fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('card_offline', 'Card went offline'), ('card_online', 'Card back online'), ('renewal_warning', 'Renewal reminder'), ('trial_ended', 'Trial ended'), ('admin_action', 'Admin action'), ('payment_received', 'Payment received')], max_length=32)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=250)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='cards_usern_user_id_6ce917_idx')],
            },
        ),
    ]
