# Generated by Django 5.2.5 on 2026-07-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0024_backfill_card_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bkash_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='bkash_next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='bkash_payer_msisdn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='bkash_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='bkash_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='bkash_subscription_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='bkash_trx_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
