# Generated by Django 5.2.5 on 2026-07-23 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0025_payment_bkash_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('title_bn', models.CharField(blank=True, help_text='Bangla title (optional)', max_length=140)),
                ('description', models.TextField()),
                ('description_bn', models.TextField(blank=True, help_text='Bangla description (optional)')),
                ('applies_to', models.CharField(choices=[('all', 'All paid plans'), ('pro', 'Pro yearly only'), ('lifetime', 'Lifetime only'), ('free_renewal', 'Free-plan yearly renewal only')], default='all', max_length=20)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent off'), ('amount', 'Flat amount off (BDT)')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percent (0-100) or flat BDT', max_digits=8)),
                ('coupon_code', models.CharField(blank=True, db_index=True, help_text='Optional — leave blank for auto-apply banner', max_length=30)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('icon', models.CharField(choices=[('sparkles', 'Sparkles'), ('gift', 'Gift'), ('flame', 'Flame'), ('percent', 'Percent'), ('badge-check', 'Badge check'), ('star', 'Star'), ('zap', 'Zap'), ('trophy', 'Trophy'), ('party-popper', 'Party popper'), ('rocket', 'Rocket')], default='sparkles', max_length=24)),
                ('color', models.CharField(default='#7c3aed', help_text='Hex color for the badge', max_length=7)),
                ('show_on_landing', models.BooleanField(default=True)),
                ('show_on_dashboard', models.BooleanField(default=True, help_text='Show a banner on free-user dashboards')),
                ('show_as_popup', models.BooleanField(default=False, help_text='Show once as a popup on the free-user dashboard')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='cards_offer_is_acti_434496_idx'), models.Index(fields=['coupon_code'], name='cards_offer_coupon__dc4f94_idx')],
            },
        ),
    ]
